### ISSUE TITLE
Preview Not Updating In Home App

### ISSUE THREAD

**Issue by erfind** [legotheboss/YouTube-files#10]
The preview for the camera is not showing up as a camera image in the HomeApp. Instead it shows a photo of a modern house. Any ideas?

![](http://i.imgur.com/urRqxNt.jpg)

**Comment by legotheboss** [comment]
Did you set a password to Motioneye? This is the most common cause of this issue...

**Comment by erfind** [comment]
I did indeed, is there any way to have it secured and still have the preview update?

**Comment by legotheboss** [comment]
@erfinb Unfortunately not...
