### ISSUE TITLE
Pi homebridge with yi home cam

### ISSUE THREAD

**Issue by Lestercity** [legotheboss/YouTube-files#11]
Dear Lego the boss. Reading through all the comments I saw you were the only one that seem to have the yi home cam running without issues in homekit through homebridge with plugin. Could you tell me how to do it step by step. Really would love to have this running. Thx for the great work.

**Comment by legotheboss** [comment]
@Lestercity do you have a different firmware running on your Yi Cam? I use my camera with [this](https://github.com/fritz-smh/yi-hack) firmware so that I can get a RTSP stream to use with HAP-NodeJS

**Comment by legotheboss** [comment]
@Lestercity uploaded my YiCamera's Camera.js file [here](https://raw.githubusercontent.com/legotheboss/YouTube-files/master/HAPCamera/YiCamera/Camera.js). Replace your lib/Camera.js with this one. Then open the file and change the IP address in the second line to your respective Yi Camera IP address. Then run CameraCore.js and everything should work. 

Make sure you have my build of FFmpeg, which can be found [here](https://github.com/legotheboss/YouTube-files/blob/master/ffmpeg_3.1.4-1_armhf.deb). Download and install this package along with the latest HAP-NodeJS for all to work. 

Best of luck!

**Comment by AdySan** [comment]
I'm in the market for a Yi cam. Would you still recommend this or rather the homebridge plugin? Also just to be sure, you got audio working in the yi camera too?

**Comment by legotheboss** [comment]
@AdySan the homebridge plugin and this are practically the same thing. As for the camera, it works great. The stock firmware is a bit annoying but other than that, everything is good. As for the audio, I haven't gotten it working yet, but I'm going to be working on it this summer when I finally get some time away from school.

**Comment by AdySan** [comment]
@legotheboss thanks, I just bought one, will try the yi-hack firmware for sure. Yeah, no audio is a but if a bummer, but I'm sure you'll figure it out. Thanks! Until then good old vpn in and rtsp with VLC.

**Comment by AdySan** [comment]
Just got this camera. Any chance you can confirm the firmware version you had before applying the hack? Did you have to downgrade it?

**Comment by montanaishome** [comment]
Just bought one of the yi outdoor cameras on amazon prime day.  Would love to get it working on home bridge.  I have uploaded the Camera.js file to /lib on my Rpi (changing the IP to that on my network) and installed FFmpeg.  Pretty sure I need to add a RTSP stream address to my config.json file, but I can't seem to figure out how to get that stream from the camera?  Any help or suggestions?
