### ISSUE TITLE
I can connect many camera in HAP-NodeJS ?

### ISSUE THREAD

**Issue by Maxmudjon** [legotheboss/YouTube-files#12]
and how can I set up separately ?
I would like to like this

// Publish the camera on the local network.
cameraAccessory.publish({
username: "EC:22:3D:D3:CE:CE",
port: 51062,
pincode: "000-00-000",
category: Accessory.Categories.CAMERA,
ipsi: "rtsp://192.168.1.115/live1.264?user=abs&passwd=123"
}, true);

**Comment by legotheboss** [comment]
Not sure how to achieve this. As stated before, HAP only supports one camera per node.
