### ISSUE TITLE
Raspberry Light doesn't pair

### ISSUE THREAD

**Issue by nik012003** [legotheboss/YouTube-files#14]
I have an iPhone 6 on 10.2 Jailbroken,
Core.js starts correctly but the iPhone doesn't pair with the accessory 
http://imgur.com/uWw0VyH
http://imgur.com/msVfSxb

**Comment by legotheboss** [comment]
Check to make sure your connection code is correct and also change the username in the accessory file. Also delete the persist directory 

''''
sudo rm -rf /home/pi/HAP-NodeJS/persist
''''
