### ISSUE TITLE
CameraCore.js and wifi out of home

### ISSUE THREAD

**Issue by gjouanjean** [legotheboss/YouTube-files#15]
Hello ! 
Thank you very much for your videos !

I used CameraCore.js, and since 2 weeks no problem with local wifi but it doesn't work with LTE. 
My sonoff work perfectly in wifi and LTE but my camera no.

Do you have an idea ?

Thank you very much !

**Comment by legotheboss** [comment]
Do you have an Apple TV 3rd gen or a Apple TV 4th gen?
