### ISSUE TITLE
Raspberry Pi 3 + Livolo Switches

### ISSUE THREAD

**Issue by Playboybra** [legotheboss/YouTube-files#16]
@legotheboss, first, thank you for your youtube videos. They give a great help for us! (Ps: I'm from Brazil).

Because I started watch your videos, i'm on a project that using a RPi 3 and an RF transmitter create an Apple HomeBridge to control all Livolo switches (some 50 gangs) and Sonoff switches through the Home application and by voice control (Siri).

I think the initial idea is quite simple, but I'm finding it very difficult to complete, since my knowledge of RPi is few.

I bought a RPi 3 kit with Screen, receiver and RF transmitter, Livolo wireless switches (several with 3 gangs each) and Livolo remote control (VL-RMT-04) that controls up to 27 circuits.

Because of your videos, I know how to install HomeBridge on Raspberry Pi, Hap-NodeJs and how to control Sonoff.

My problem now is how to controll the Livolo switches.

In this site (http://www.instructables.com/id/Controlling-a-Livolo-RF-Light-Switch-Using-a-Raspb/) they teaches how to control 1 gang 1 way switch, but I have several 3 gangs 2 ways and I need to control 27 circuits plus scene mode. 

I alread located this files:
https://github.com/midorineko/rpi_automation/blob/master/livolo.py
https://github.com/platenspeler/LamPI-3.x/tree/master/transmitters/livolo
https://github.com/crankru/nodejs-livolo
https://github.com/rafflesgun/pi-livolo
https://github.com/burilovmv/livolo-switch

But my problem is that I can't get the RPi to controll all my 50 circuits.

Please, can you help me and made a tutorial how to? I'm sure thats your answer can help a lot of people around the world.

Thanks.

**Comment by legotheboss** [comment]
@Playboybra can you contact me via twitter? I can help you faster and quicker. There is a way to do it. Here is a summarized version...

First, run my light tutorial. This will install files that we can use to get started.

Once you run this, it should install:

- NodeJS module connection to python
- HAP-NodeJS accessories for a light accessory

After you finish the lights tutorial, you can create your python files that control the necessary accessories. Create a file to turn on the outlet, and as well as turn off the outlet. Once you do this, open Light_accessory.js

Edit lines 24 and 25
````
if(status) cmd.run('sudo python /home/pi/HAP-NodeJS/python/light1.py ' + relayPin);
else cmd.run('sudo python /home/pi/HAP-NodeJS/python/light0.py ' + relayPin);
````

Change the command insde the cmd.run to reflect your python files.
Ex:
````
if(status) cmd.run('sudo python ENTER OUTLET ON FILE HERE');
else cmd.run('sudo python ENTER OUTLET OFF FILE HERE');
````

You can keep going by duplicating this Light_accessory.js file and process for your 27 outlets. Make sure each file ends with _accessory.js ending and has a different: UDID, accessory name, and username.

Sorry for the late reply, I don't check my GitHub issues page much. For a quicker response (<24 hours), please contact me thru my Twitter DMs [here](twitter.com/Quick_Pi).
