### ISSUE TITLE
No Response from HomeKit

### ISSUE THREAD

**Issue by djedyed** [legotheboss/YouTube-files#19]
This what I get when I do an npm test
:~ $ npm test
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "test"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
 and yet my HAP-NodeJS is running
:~/HAP-NodeJS $ ls
accessories     CameraCore.js  index.js  LICENSE       package.json  python
BridgedCore.js  Core.js        lib       node_modules  persist       README.md
pi@raspberrypi:~/HAP-NodeJS $ sudo forever start BridgedCore.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: BridgedCore.js

**Comment by legotheboss** [comment]
Ok, have you tried running HAP-NodeJS without the forever? Is the HAP-NodeJS working properly when run directly (sudo node BridgedCore.js)?
