### ISSUE TITLE
problem with parsing accessories

### ISSUE THREAD

**Issue by chris-008** [legotheboss/YouTube-files#22]
Hi there,
fist of all thank you a lot for your helpfull tutorials! They are a big contribution to the whole scene.
I am trying to follow your youtube tutorial get the sonoff modules installed with the HAP node Js but can't seem to get to the parsing accessory state.
The sonoff js file is filled in correctly.

while redoing the whole scenario i met into an error:

chris@orangepizero:~$ sudo sh kaMxMM
kaMxMM: 1: cd: can't cd to /home/pi/HAP-NodeJS
Mosquitto already installed, continuing with install
kaMxMM: 13: cd: can't cd to /home/pi/HAP-NodeJS
mqtt@2.13.0 node_modules/mqtt
kaMxMM: 15: cd: can't cd to accessories/
--2017-09-30 12:23:25--  https://goo.gl/EI1rr3
Resolving goo.gl (goo.gl)... 172.217.20.110, 2a00:1450:400e:80b::200e
Connecting to goo.gl (goo.gl)|172.217.20.110|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/legotheboss/YouTube-files/master/MQTT/Sonoff/SonoffMQTT_accessory.js [following]
--2017-09-30 12:23:25--  https://raw.githubusercontent.com/legotheboss/YouTube-files/master/MQTT/Sonoff/SonoffMQTT_accessory.js
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2370 (2.3K) [text/plain]
Saving to: ‘SonoffMQTT_accessory.js’

SonoffMQTT_accessory.js                                             100%[=================================================================================================================================================================>]   2.31K  --.-KB/s    in 0.001s  

2017-09-30 12:23:25 (2.30 MB/s) - ‘SonoffMQTT_accessory.js’ saved [2370/2370]

Any idea what went wrong here?
thanks in advance,
chris

**Comment by legotheboss** [comment]
@chris-008 You did not install HAP-NodeJS. Look into this: https://youtu.be/3RmuXn8eS9s. Once you install HAP-NodeJS, come back to the Sonoff Tutorial.
