### ISSUE TITLE
I can connect with ip with motioneye

### ISSUE THREAD

**Issue by Patrykos9114** [legotheboss/YouTube-files#23]
Hi,
I did everything according to the tutorial on youtube, and everything went smoothly but there was a bug when the process was terminated on raspberry and I went to the computer for ip wlan I can not go to motioneye :( .. Any help how to solve it?

**Comment by legotheboss** [comment]
@Patrykos9114 there does seem to be an issue with the automated installation for Raspbian Stretch, I am looking into it.

**Comment by legotheboss** [comment]
Fixed
