### ISSUE TITLE
HomeKit won't update

### ISSUE THREAD

**Issue by thematriksz** [legotheboss/YouTube-files#25]
Something is wrong, it doesn't refresh in the Homekit app, it is stuck at the first (after initial setup) value. I'm running iOS 11.0.3. Any ideas?﻿

**Comment by legotheboss** [comment]
@thematriksz which tutorial does this correspond this with?

**Comment by tedyno** [comment]
I have same issue, I followed thist tut: https://www.youtube.com/watch?v=hVrl7FC_T2Y a it shows me still the same temps (I have two DS18B20), although each w1_slave file shows me already different temperature.
Thanks for any suggestions, I love your work!

**Comment by tedyno** [comment]
I figured out it was forever script that was ruining it, fixed it by stopping forever script and adding line to crontab after reboot to start Core.js
