### ISSUE TITLE
ffmpeg install error RPi 3 B+

### ISSUE THREAD

**Issue by jeylites** [legotheboss/YouTube-files#26]
@legotheboss 

Hi, thanks for putting this together! I tried running the following script on my RPI3 B+, Jessie but I'm getting error 

`git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree`

**ERROR**
`pi@raspberrypi:~ $ cd /home/pi/

pi@raspberrypi:~ $ sudo git clone https://github.com/FFmpeg/FFmpeg.git
Cloning into 'FFmpeg'...
fatal: unable to access 'https://github.com/FFmpeg/FFmpeg.git/': Could not resolve host: github.com

pi@raspberrypi:~ $ wget https://github.com/legotheboss/YouTube-files/raw/master/ffmpeg_3.1.4-1_armhf.deb
--2017-10-22 11:36:23--  https://github.com/legotheboss/YouTube-files/raw/master/ffmpeg_3.1.4-1_armhf.deb
Resolving github.com (github.com)... failed: Name or service not known.
wget: unable to resolve host address ‘github.com’`

**Comment by jeylites** [comment]
Fixed it, it was a network issue on the RPI3 part. But now I get this error 

```
pi@raspberrypi:~ $ cd FFmpeg
pi@raspberrypi:~/FFmpeg $ sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree

ERROR: OMX_Core.h header not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
pi@raspberrypi:~/FFmpeg $ 
pi@raspberrypi:~/FFmpeg $ 

```

**Comment by North46** [comment]
I have the exact same problem installing on Stretch on RPi 3.  Worked great before on Jessie..

Just found the solution. Run the following before configure.

sudo apt-get install libomxil-bellagio-dev

**Comment by legotheboss** [comment]
Thanks, will add this to the tutorial.
