### ISSUE TITLE
Light_accessory

### ISSUE THREAD

**Issue by linuxpa** [legotheboss/YouTube-files#3]
How would it be possible to change the status of the light as well as by IOS also through a gpio input?

**Comment by Maxmudjon** [comment]
I would use mqtt protocol. With this protocol can be changed and the state of light and brightness of the light through the iPhone

**Comment by legotheboss** [comment]
@linuxpa Yep, it's possible. I have updated the light_accessory.js file to allow some sort of implementation if you wanted.

**Comment by Maxmudjon** [comment]
i'm already created 😉
