### ISSUE TITLE
CameraCore.js no video stream

### ISSUE THREAD

**Issue by sassen** [legotheboss/YouTube-files#31]
Hi legotheboss,

Thank you for your tutorials, they are very useful. I did not follow your tutorial 100% because I am using RPi Zero W, and as I understood another nodejs is needed for Pi Zeros armv6.

Well, I have motioneye installed and running so no issues there. I did install hap-nodejs too and I was able to run it and link it to homekit on my Iphone (I modified CameraCore.js as you showed on your video). My problem is that I can not see the stream on the phone, I only get the default thumbnail picture from Homekit. When I open the stream it says that the camera is not responding. Any idea on what I am missing?

After installing first Stretch and then Motion Eye these are the steps I followed:

1. sudo apt-get install curl
3. sudo bash
4. sudo wget -O - https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh | bash
6. exit
7. node -v
8. sudo apt-get install -y nodejs
9. sudo apt-get install -y npm
10. sudo apt-get install libavahi-compat-libdnssd-dev
11. sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
12. cd /opt/nodejs/lib/node_modules/homebridge
13. sudo npm install --unsafe-perm bignum
14. cd /opt/nodejs/lib/node_modules/hap-nodejs/node_modules/mdns
15. sudo node-gyp BUILDTYPE=Release rebuild
18. Extra steps to solve wrong node_module_version issue
19. sudo npm uninstall homebrigde -g
20. sudo npm install -g --unsafe-perm homebridge

Last: sudo node CameraCore.js
Linked the camera in the Home app on the phone but no stream when I click on it. Camera not responding...

**Comment by sassen** [comment]
I think I am missing Camera.js... I'm travelling at the moment and cant fix it until next week.

**Comment by legotheboss** [comment]
@sassen Not sure why Camera.js was not saving itself in the HAP-NodeJS directory, but it should be resolved now. Try rerunning the tutorial and see if it works.
