### ISSUE TITLE
Multiple Cameras On Same Pi

### ISSUE THREAD

**Issue by erfind** [legotheboss/YouTube-files#33]
Hey! I am trying to figure out how to create two HomeKit Cameras with two cameras connected to my Pi and running in motionEye.  Could you help with that? :)

**Comment by legotheboss** [comment]
It is doable, but a bit complex to do. You would need to clone the HAP-NodeJS folder, edit the lib/Camera.js file to reflect your second camera's motioneye ports, edit CameraCore.js to create a new camera for HomeKit to recognize and run it on a different port as well. Once all this is done, running the second CameraCore.js should allow the Camera to function properly.
