### ISSUE TITLE
18b20 sensor in homekit?

### ISSUE THREAD

**Issue by lisergio** [legotheboss/YouTube-files#34]
Is it possible to send by mqtt only the value of the temperature read by the tasmota and the sensor 18b20 to the homekit server?
I have tried to read the value sent by tasmota, but send:
 {"Time":"2018-04-02T17:09:50","DS18B20":{"Temperature":21.9},"TempUnit":"C"}
and it is not possible to read only the temperature.
thanks

**Comment by legotheboss** [comment]
Yes, it is completely possible. In SonoffTemperature_accessory.js, replace line 4 to say:

Original
````var sensorType = 'DHT22';```` 

New
````var sensorType = 'DS18B20';````

**Comment by lisergio** [comment]
Thanks!
