### ISSUE TITLE
MQTT Fan_accessory.js

### ISSUE THREAD

**Issue by Maxmudjon** [legotheboss/YouTube-files#4]
Fan accessory for HAP-NodeJS
[MQTT_Fan_accessory.txt](https://github.com/legotheboss/YouTube-files/files/585308/MQTT_Fan_accessory.txt)

Fan accessory for ESP8266
[Ventilator_MQTT.txt](https://github.com/legotheboss/YouTube-files/files/585320/Ventilator_MQTT.txt)

The fan with three modes

**Comment by legotheboss** [comment]
@Maxmudjon can you provide the ESP8266 file with English Translation? I can understand some of it but got lost in a few places as well...

**Comment by Maxmudjon** [comment]
ok I'll translate in English

**Comment by Maxmudjon** [comment]
the fan runs with three modes of low medium high in this code
