### ISSUE TITLE
Require reboot to activate newly installed FFmpeg

### ISSUE THREAD

**Issue by paulz** [legotheboss/YouTube-files#41]
Thank you for the great tutorial!

https://github.com/legotheboss/YouTube-files/wiki/(RPi)-Compile-FFmpeg-with-the-OpenMAX-H.264-GPU-acceleration

mentioned that `sudo make install` installs newly build `ffmpeg`, but if you had FFmpeg installed before you need to `sudo reboot now` to activate the new one.

**Comment by legotheboss** [comment]
Thanks :)
