### ISSUE TITLE
a font used in Apple Homekit PIN CODE ?

### ISSUE THREAD

**Issue by Maxmudjon** [legotheboss/YouTube-files#5]
a font used in Apple Homekit PIN CODE ?
eg Verdana or Times New Roman ...

**Comment by legotheboss** [comment]
@Maxmudjon [Here](https://github.com/legotheboss/YouTube-files/blob/master/pairing.png) is the pairing code.

**Comment by Maxmudjon** [comment]
I myself created this font in the font creator

**Comment by gbougakov** [comment]
Can U send  it to me

**Comment by Maxmudjon** [comment]
give mail

**Comment by gbougakov** [comment]
george at georgenet dot gq

**Comment by lodogg** [comment]
Hi Maxmodjon, can you send me the font? Here is my email: verzo85 at gmail dot com

**Comment by Maxmudjon** [comment]
Sent by mail

**Comment by net32** [comment]
can you send for me ? please! email: isaias _ finger at hotmail dot com

**Comment by gbougakov** [comment]
Here is a link
https://app.box.com/s/10ofyppxyz9kmvbwoyjawmnletv1e2y8

**Comment by gbougakov** [comment]
@net32 ⬆︎

**Comment by net32** [comment]
thank you!
