### ISSUE TITLE
HomeKit Camera

### ISSUE THREAD

**Issue by erfind** [legotheboss/YouTube-files#7]
Greetings!

I was wondering what the lowest version of the raspberry pic an be used and where to buy it. I have already purchased three PS Eye Cams but was wondering if the Raspberry Pi zero would work or not or if you have another place to look up info on the different versions. 

Thank you!

**Comment by legotheboss** [comment]
Raspberry Pi Zero should work perfectly fine, I use it with my setup. The initial paring process takes just a bit longer for Pi Zero. Make sure you have a hub to plug in both the USB Wi-Fi and as well as the PS Eye.
