### ISSUE TITLE
Motion Eye and Motion Sensing

### ISSUE THREAD

**Issue by erfind** [legotheboss/YouTube-files#8]
Greetings!

I am loving your implementation of the PS Eye Camera, can this also be used as a motion sensor with HomeKit?  If so, how would I go about that? Thank you for all of your work!!!

Sincerely,

Ethan

**Comment by legotheboss** [comment]
@erfinb Working on an implementation on for some time... Should be ready soon...

**Comment by legotheboss** [comment]
f57ff31 solved this
